<a href="https://colab.research.google.com/github/Srikhanth14/Data_Analysis_Projects/blob/main/HealthCare_Resource_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import the Necessary Libraries**

In [48]:
import pandas as pd
import numpy as np

# **Data Collection and Processing**

In [49]:
#Loading the Datasets
data = pd.read_csv("modified_healthcare_dataset.csv")

In [50]:
# Display first three rows of the dataset
data.head(3)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,19,Female,AB+,Infections,2024-01-31,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2024-02-07,Azithromycin,Normal,7
1,Leslie Terry,15,Female,B-,Flu,2019-08-20,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,2019-08-22,Tamiflu,Abnormal,2
2,Danny Smith,50,Female,A+,Cancer,2022-09-22,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214065,205,Elective,2022-10-30,Cisplatin,Inconclusive,38

In [51]:
# Display last four rows of the dataset
data.tail(4)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
55496,Kyle Perez,63,Male,A+,Heart Disease,2020-01-23,Taylor Sullivan,UI Health (University of Illinois Hospital),Medicare,26828.223456,316,Emergency,2020-03-07,Statins,Abnormal,44
55497,Heather Wang,28,Female,O+,Asthma,2020-07-13,Joe Jacobs DVM,Northwestern Memorial Hospital,Cigna,6041.030866,347,Elective,2020-07-16,Montelukast,Normal,3
55498,Jennifer Jones,75,Male,O+,Cancer,2019-05-25,Kimberly Curry,UChicago Medicine,Aetna,44495.656362,321,Emergency,2019-07-11,Methotrexate,Abnormal,47
55499,James Garcia,53,Female,O+,Diabetes,2024-04-02,Dennis Warren,Loyola University Medical Center,Cigna,15953.455966,448,Emergency,2024-04-12,Insulin,Abnormal,10

In [52]:
#Display the Sample of any 2 rows from the dataset
data.sample(2)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
48721,Kimberly Guzman Dds,30,Male,A-,Obesity,2020-01-24,Raymond Miller,UI Health (University of Illinois Hospital),Medicare,5418.212652,352,Elective,2020-01-29,Phentermine,Abnormal,5
42386,Sara Holland,44,Female,AB-,Flu,2021-03-15,Mark Lee,UI Health (University of Illinois Hospital),UnitedHealthcare,1561.333600,438,Urgent,2021-03-17,Tamiflu,Abnormal,2

In [53]:
#Print the Dimensions of the dataset
print("Number of Rows: ", data.shape[0])
print("Number of Columns: ", data.shape[1])

Number of Rows:  55500
Number of Columns:  16

In [54]:
#Displaying all column names in the Dataset
for col in data.columns:
  print(col)

Name
Age
Gender
Blood Type
Medical Condition
Date of Admission
Doctor
Hospital
Insurance Provider
Billing Amount
Room Number
Admission Type
Discharge Date
Medication
Test Results
Length of Stay

In [55]:
#Checking the Data type of Columns in the Dataset
data.dtypes.to_frame(name="Data_Type")

                   Data_Type
Name                  object
Age                    int64
Gender                object
Blood Type            object
Medical Condition     object
Date of Admission     object
Doctor                object
Hospital              object
Insurance Provider    object
Billing Amount       float64
Room Number            int64
Admission Type        object
Discharge Date        object
Medication            object
Test Results          object
Length of Stay         int64

In [56]:
# Checking any null values present in the each column
if data.isnull().sum().sum() == 0:
  print("No null values present in the dataset")
else:
  print("Null values present in the dataset")

No null values present in the dataset

In [57]:
print(data.isnull().sum())

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Length of Stay        0
dtype: int64

In [58]:
#Checking any duplicate values present in the Dataset
if data.duplicated().sum() == 0:
  print("Duplicate values doesn't exist in the dataset")
else:
  print("Duplicate values exist in the dataset")

Duplicate values doesn't exist in the dataset

In [59]:
#Statistical Summary of the Dataset
data.describe()

                Age  Billing Amount   Room Number  Length of Stay
count  55500.000000    55500.000000  55500.000000    55500.000000
mean      48.001622    21835.044635    301.134829       17.841009
std       21.105827    23574.413594    115.243069       20.272294
min        5.000000      500.220989    101.000000        1.000000
25%       32.000000     4195.525741    202.000000        4.000000
50%       50.000000    11089.537763    302.000000        8.000000
75%       65.000000    35887.703406    401.000000       28.000000
max       90.000000    99997.797977    500.000000       89.000000

In [60]:
#Overview of the Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15  Length of Stay      55500 non-null  int64
dtypes: float64(1), int64(3), object(12)
memory usage: 6.8+ MB

In [61]:
#Identifying the Total unique values in Each Column
data.nunique()

Name                  40235
Age                      86
Gender                    2
Blood Type                8
Medical Condition         8
Date of Admission      1827
Doctor                40341
Hospital                  4
Insurance Provider        5
Billing Amount        55500
Room Number             400
Admission Type            4
Discharge Date         1901
Medication               23
Test Results              3
Length of Stay           89
dtype: int64

In [62]:
print("Frequency of Each Categorical Variables",'\n')
Categorical_Target_Columns = ["Gender","Blood Type", "Medical Condition", "Doctor", "Hospital", "Insurance Provider", "Admission Type", "Medication", "Test Results"]

for categorical_columns in Categorical_Target_Columns:
    print(data[categorical_columns].value_counts())
    print("-"*50)

Frequency of Each Categorical Variables

Gender
Female    27955
Male      27545
Name: count, dtype: int64
--------------------------------------------------
Blood Type
O+     15696
A+     15573
B+      5457
AB-     4485
B-      4408
O-      3341
A-      3301
AB+     3239
Name: count, dtype: int64
--------------------------------------------------
Medical Condition
Flu              7046
Diabetes         7005
Obesity          6994
Cancer           6940
Asthma           6908
Heart Disease    6900
Alzheimer’s      6861
Infections       6846
Name: count, dtype: int64
--------------------------------------------------
Doctor
Michael Smith      27
John Smith         22
Robert Smith       22
Michael Johnson    20
James Smith        20
                   ..
Keith Ortiz         1
Timothy Chapman     1
Terri Collins       1
Jill Jacobson       1
Scott Coleman       1
Name: count, Length: 40341, dtype: int64
--------------------------------------------------
Hospital
Northwestern Memorial Hospital                 14070
UI Health (University of Illinois Hospital)    13950
UChicago Medicine                              13870
Loyola University Medical Center               13610
Name: count, dtype: int64
--------------------------------------------------
Insurance Provider
Cigna               11183
UnitedHealthcare    11142
Blue Cross          11134
Medicare            11038
Aetna               11003
Name: count, dtype: int64
--------------------------------------------------
Admission Type
Emergency    20104
Elective     13280
Urgent       11816
Routine      10300
Name: count, dtype: int64
--------------------------------------------------
Medication
Metformin        4653
Zanamivir        2391
Methotrexate     2375
Glipizide        2362
Orlistat         2351
Insulin          2340
Aspirin          2337
Prednisone       2333
Oseltamivir      2329
Tamiflu          2326
Montelukast      2313
Memantine        2312
Azithromycin     2312
Amoxicillin      2311
Beta-blockers    2297
Doxorubicin      2296
Phentermine      2293
Donepezil        2292
Cisplatin        2269
Statins          2266
Albuterol        2262
Rivastigmine     2257
Ciprofloxacin    2223
Name: count, dtype: int64
--------------------------------------------------
Test Results
Abnormal        27784
Normal          17453
Inconclusive    10263
Name: count, dtype: int64
--------------------------------------------------

In [63]:
print("Distribution of Categorical Variables in Percentage",'\n')
for categorical_columns in Categorical_Target_Columns:
    print(data[categorical_columns].value_counts(normalize=True)*100)
    print("-"*50)

Distribution of Categorical Variables in Percentage

Gender
Female    50.369369
Male      49.630631
Name: proportion, dtype: float64
--------------------------------------------------
Blood Type
O+     28.281081
A+     28.059459
B+      9.832432
AB-     8.081081
B-      7.942342
O-      6.019820
A-      5.947748
AB+     5.836036
Name: proportion, dtype: float64
--------------------------------------------------
Medical Condition
Flu              12.695495
Diabetes         12.621622
Obesity          12.601802
Cancer           12.504505
Asthma           12.446847
Heart Disease    12.432432
Alzheimer’s      12.362162
Infections       12.335135
Name: proportion, dtype: float64
--------------------------------------------------
Doctor
Michael Smith      0.048649
John Smith         0.039640
Robert Smith       0.039640
Michael Johnson    0.036036
James Smith        0.036036
                     ...
Keith Ortiz        0.001802
Timothy Chapman    0.001802
Terri Collins      0.001802
Jill Jacobson      0.001802
Scott Coleman      0.001802
Name: proportion, Length: 40341, dtype: float64
--------------------------------------------------
Hospital
Northwestern Memorial Hospital                 25.351351
UI Health (University of Illinois Hospital)    25.135135
UChicago Medicine                              24.990991
Loyola University Medical Center               24.522523
Name: proportion, dtype: float64
--------------------------------------------------
Insurance Provider
Cigna               20.149550
UnitedHealthcare    20.075676
Blue Cross          20.061261
Medicare            19.888288
Aetna               19.825225
Name: proportion, dtype: float64
--------------------------------------------------
Admission Type
Emergency    36.223423
Elective     23.927928
Urgent       21.290090
Routine      18.558559
Name: proportion, dtype: float64
--------------------------------------------------
Medication
Metformin        8.383784
Zanamivir        4.308108
Methotrexate     4.279279
Glipizide        4.255856
Orlistat         4.236036
Insulin          4.216216
Aspirin          4.210811
Prednisone       4.203604
Oseltamivir      4.196396
Tamiflu          4.190991
Montelukast      4.167568
Memantine        4.165766
Azithromycin     4.165766
Amoxicillin      4.163964
Beta-blockers    4.138739
Doxorubicin      4.136937
Phentermine      4.131532
Donepezil        4.129730
Cisplatin        4.088288
Statins          4.082883
Albuterol        4.075676
Rivastigmine     4.066667
Ciprofloxacin    4.005405
Name: proportion, dtype: float64
--------------------------------------------------
Test Results
Abnormal        50.061261
Normal          31.446847
Inconclusive    18.491892
Name: proportion, dtype: float64
--------------------------------------------------

# **Data Cleaning and Pre-Processing**

In [64]:
#Converting Date Columns to Date Type
data["Date of Admission"] = pd.to_datetime(data["Date of Admission"])
data["Discharge Date"] = pd.to_datetime(data["Discharge Date"])

In [65]:
print(data[["Date of Admission","Discharge Date"]].dtypes)

Date of Admission    datetime64[ns]
Discharge Date       datetime64[ns]
dtype: object

In [66]:
data[["Date of Admission","Discharge Date"]].sample(2)

      Date of Admission Discharge Date
13582        2022-03-19     2022-05-02
23950        2021-05-05     2021-05-09

In [67]:
#Admission and Discharge Date Validation
Date_Validation = data['Discharge Date'] > data['Date of Admission']
print("Are all discharge date valid: ", Date_Validation.all())
print("Total Invalid rows in Date_Validation: ",(~Date_Validation).sum())

Are all discharge date valid:  True
Total Invalid rows in Date_Validation:  0

In [68]:
#Length of Stay Validation
Calculated_Length_Of_Stay = (data['Discharge Date'] - data['Date of Admission']).dt.days
Length_Of_Stay_Validation = data['Length of Stay']== Calculated_Length_Of_Stay
print("Does Length of Stay match the Calculated Length_Of_Stay numbers: ", Length_Of_Stay_Validation.all())
print("Total Invalid rows in Length_of_Stay_Validation: ",(~Length_Of_Stay_Validation).sum())

Does Length of Stay match the Calculated Length_Of_Stay numbers:  True
Total Invalid rows in Length_of_Stay_Validation:  0

In [69]:
#Billing Amount Validation
Billing_Validation = data['Billing Amount']>0
print("Does Billing Amount is greater than zero: ", Billing_Validation.all())
print("Total Invalid rows in Billing Amount: ",(~Billing_Validation).sum())

Does Billing Amount is greater than zero:  True
Total Invalid rows in Billing Amount:  0

In [70]:
#Age Validation
Age_Validation = data['Age'].between(0,100)
print("Are all ages within the valid ranges: ", Age_Validation.all())
print("Total Invalid Values in Ages: ",(~Age_Validation).sum())

Are all ages within the valid ranges:  True
Total Invalid Values in Ages:  0

In [71]:
#Cross checking the consistency of Categorical Target Columns
Categorical_Target_Columns = ["Gender","Blood Type", "Medical Condition", "Hospital", "Insurance Provider", "Admission Type"]

for categorical_columns in Categorical_Target_Columns:
    print(categorical_columns)
    print(data[categorical_columns].unique())
    print("-"*50)

Gender
['Female' 'Male']
--------------------------------------------------
Blood Type
['AB+' 'B-' 'A+' 'O+' 'O-' 'AB-' 'A-' 'B+']
--------------------------------------------------
Medical Condition
['Infections' 'Flu' 'Cancer' 'Asthma' 'Heart Disease' 'Alzheimer’s'
 'Diabetes' 'Obesity']
--------------------------------------------------
Hospital
['Northwestern Memorial Hospital'
 'UI Health (University of Illinois Hospital)' 'UChicago Medicine'
 'Loyola University Medical Center']
--------------------------------------------------
Insurance Provider
['Blue Cross' 'UnitedHealthcare' 'Aetna' 'Cigna' 'Medicare']
--------------------------------------------------
Admission Type
['Emergency' 'Elective' 'Routine' 'Urgent']
--------------------------------------------------

# **Feature Engineering**

In [72]:
#Extracting the day, month and year from the Admission Date
data['Admission Day'] = data['Date of Admission'].dt.day_name()
data['Admission Month'] = data['Date of Admission'].dt.month
data['Admission Year'] = data['Date of Admission'].dt.year

In [73]:
print("Unique values in Admission Year")
print(data["Admission Year"].unique())

Unique values in Admission Year
[2024 2019 2022 2020 2023 2021]

In [74]:
print("Unique values in Admission Week Day")
print(data["Admission Day"].unique())

Unique values in Admission Week Day
['Wednesday' 'Tuesday' 'Thursday' 'Monday' 'Sunday' 'Friday' 'Saturday']

In [75]:
print("Unique values in Admission Month")
print(data["Admission Month"].unique())

Unique values in Admission Month
[ 1  8  9 11 12  7  5  4 10  6  3  2]

In [76]:
print("Frequency values in Admission Year", '\n')
print(data.groupby("Admission Year").size().sort_values(ascending=False))

Frequency values in Admission Year

Admission Year
2020    11285
2023    11026
2022    11017
2021    10931
2019     7387
2024     3854
dtype: int64

In [77]:
print("Frequency values in Admission Month", '\n')
print(data.groupby("Admission Month").size().sort_values(ascending=False))

Frequency values in Admission Month

Admission Month
8     4832
7     4812
6     4699
1     4692
10    4678
3     4672
12    4649
5     4599
11    4548
9     4546
4     4518
2     4255
dtype: int64

In [78]:
print("Frequency values in Admission Week Day", '\n')
print(data.groupby("Admission Day").size().sort_values(ascending=False))

Frequency values in Admission Week Day

Admission Day
Thursday     7989
Tuesday      7982
Wednesday    7950
Sunday       7920
Saturday     7901
Friday       7892
Monday       7866
dtype: int64

#**One-Hot Encoding**

In [79]:
#Converting Required Categorical Features to Numeric using One-Hot Encoding
Encoded_Data=pd.get_dummies(data, columns=["Gender","Blood Type","Medical Condition","Hospital","Insurance Provider","Admission Day","Admission Month","Admission Year"],drop_first=True,dtype=int)
Encoded_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 55 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Name                                                  55500 non-null  object
 1   Age                                                   55500 non-null  int64
 2   Date of Admission                                     55500 non-null  datetime64[ns]
 3   Doctor                                                55500 non-null  object
 4   Billing Amount                                        55500 non-null  float64
 5   Room Number                                           55500 non-null  int64
 6   Admission Type                                        55500 non-null  object
 7   Discharge Date                                        55500 non-null  datetime64[ns]
 8   Medication                                            55500 non-null  object
 9   Test Results                                          55500 non-null  object
 10  Length of Stay                                        55500 non-null  int64
 11  Gender_Male                                           55500 non-null  int64
 12  Blood Type_A-                                         55500 non-null  int64
 13  Blood Type_AB+                                        55500 non-null  int64
 14  Blood Type_AB-                                        55500 non-null  int64
 15  Blood Type_B+                                         55500 non-null  int64
 16  Blood Type_B-                                         55500 non-null  int64
 17  Blood Type_O+                                         55500 non-null  int64
 18  Blood Type_O-                                         55500 non-null  int64
 19  Medical Condition_Asthma                              55500 non-null  int64
 20  Medical Condition_Cancer                              55500 non-null  int64
 21  Medical Condition_Diabetes                            55500 non-null  int64
 22  Medical Condition_Flu                                 55500 non-null  int64
 23  Medical Condition_Heart Disease                       55500 non-null  int64
 24  Medical Condition_Infections                          55500 non-null  int64
 25  Medical Condition_Obesity                             55500 non-null  int64
 26  Hospital_Northwestern Memorial Hospital               55500 non-null  int64
 27  Hospital_UChicago Medicine                            55500 non-null  int64
 28  Hospital_UI Health (University of Illinois Hospital)  55500 non-null  int64
 29  Insurance Provider_Blue Cross                         55500 non-null  int64
 30  Insurance Provider_Cigna                              55500 non-null  int64
 31  Insurance Provider_Medicare                           55500 non-null  int64
 32  Insurance Provider_UnitedHealthcare                   55500 non-null  int64
 33  Admission Day_Monday                                  55500 non-null  int64
 34  Admission Day_Saturday                                55500 non-null  int64
 35  Admission Day_Sunday                                  55500 non-null  int64
 36  Admission Day_Thursday                                55500 non-null  int64
 37  Admission Day_Tuesday                                 55500 non-null  int64
 38  Admission Day_Wednesday                               55500 non-null  int64
 39  Admission Month_2                                     55500 non-null  int64
 40  Admission Month_3                                     55500 non-null  int64
 41  Admission Month_4                                     55500 non-null  int64
 42  Admission Month_5                                     55500 non-null  int64
 43  Admission Month_6                                     55500 non-null  int64
 44  Admission Month_7                                     55500 non-null  int64
 45  Admission Month_8                                     55500 non-null  int64
 46  Admission Month_9                                     55500 non-null  int64
 47  Admission Month_10                                    55500 non-null  int64
 48  Admission Month_11                                    55500 non-null  int64
 49  Admission Month_12                                    55500 non-null  int64
 50  Admission Year_2020                                   55500 non-null  int64
 51  Admission Year_2021                                   55500 non-null  int64
 52  Admission Year_2022                                   55500 non-null  int64
 53  Admission Year_2023                                   55500 non-null  int64
 54  Admission Year_2024                                   55500 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(47), object(5)
memory usage: 23.3+ MB

In [80]:
print(Encoded_Data.columns)

Index(['Name', 'Age', 'Date of Admission', 'Doctor', 'Billing Amount',
       'Room Number', 'Admission Type', 'Discharge Date', 'Medication',
       'Test Results', 'Length of Stay', 'Gender_Male', 'Blood Type_A-',
       'Blood Type_AB+', 'Blood Type_AB-', 'Blood Type_B+', 'Blood Type_B-',
       'Blood Type_O+', 'Blood Type_O-', 'Medical Condition_Asthma',
       'Medical Condition_Cancer', 'Medical Condition_Diabetes',
       'Medical Condition_Flu', 'Medical Condition_Heart Disease',
       'Medical Condition_Infections', 'Medical Condition_Obesity',
       'Hospital_Northwestern Memorial Hospital', 'Hospital_UChicago Medicine',
       'Hospital_UI Health (University of Illinois Hospital)',
       'Insurance Provider_Blue Cross', 'Insurance Provider_Cigna',
       'Insurance Provider_Medicare', 'Insurance Provider_UnitedHealthcare',
       'Admission Day_Monday', 'Admission Day_Saturday',
       'Admission Day_Sunday', 'Admission Day_Thursday',
       'Admission Day_Tuesday', 'Admission Day_Wednesday', 'Admission Month_2',
       'Admission Month_3', 'Admission Month_4', 'Admission Month_5',
       'Admission Month_6', 'Admission Month_7', 'Admission Month_8',
       'Admission Month_9', 'Admission Month_10', 'Admission Month_11',
       'Admission Month_12', 'Admission Year_2020', 'Admission Year_2021',
       'Admission Year_2022', 'Admission Year_2023', 'Admission Year_2024'],
      dtype='object')

# **Label Encoding**

In [81]:
#Encoding the Target Feature by using Label Encoding i,e Mapping Function
Admission_Type_Mapping = {'Emergency': 0, 'Elective': 1, 'Urgent': 2,'Routine':3}
Encoded_Data['Admission Type'] = Encoded_Data['Admission Type'].map(Admission_Type_Mapping)

In [82]:
Encoded_Data['Admission Type'].value_counts()

Admission Type
0    20104
1    13280
2    11816
3    10300
Name: count, dtype: int64

In [83]:
Encoded_Data.sample(2)

,Name,Age,Date of Admission,Doctor,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,...,Admission Month_8,Admission Month_9,Admission Month_10,Admission Month_11,Admission Month_12,Admission Year_2020,Admission Year_2021,Admission Year_2022,Admission Year_2023,Admission Year_2024
32752,Andrew Jennings,42,2022-06-12,Sean Pena,4781.933400,121,2,2022-06-15,Amoxicillin,Abnormal,...,0,0,0,0,0,0,0,1,0,0
21194,Margaret Curry,30,2023-10-06,Luke Schultz,5856.573992,481,0,2023-10-09,Prednisone,Normal,...,0,0,1,0,0,0,0,0,1,0

# **Model Selection**

In [84]:
from sklearn.model_selection import train_test_split   #Splitting the Data
from sklearn.linear_model import LogisticRegression    #Logistic Regression
from sklearn.tree import DecisionTreeClassifier        #Decision Tree
from sklearn.ensemble import RandomForestClassifier    #Random Forest Classification
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score  #Model Evaluation Parameters

In [85]:
#Splitting the Training and Target Features
x=Encoded_Data.drop(['Name','Date of Admission', 'Doctor','Billing Amount','Room Number','Admission Type','Discharge Date', 'Medication','Test Results', 'Length of Stay'], axis=1)
y=Encoded_Data['Admission Type']

In [86]:
print(x.shape,y.shape)

(55500, 45) (55500,)

In [87]:
#Training and Testing the Data
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=2, stratify=y)

In [88]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(44400, 45) (11100, 45) (44400,) (11100,)

In [89]:
Models={
'Logistic Regression':LogisticRegression(max_iter=3000,solver='saga',class_weight='balanced'),
'Decision Tree':DecisionTreeClassifier(),
'Random Forest':RandomForestClassifier(random_state=2,class_weight='balanced')
 }

# **Model Evaluation**

In [90]:
#Creating an Empty Result Set
Results = []

In [91]:
#Training and Evaluating the Each Model
for model_name, model in Models.items():
      model.fit(X_train, Y_train)
      Y_pred = model.predict(X_test)

      accuracy = accuracy_score(Y_test, Y_pred)*100
      precision = precision_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      recall = recall_score(Y_test, Y_pred, average='weighted',zero_division=0)*100
      f1 = f1_score(Y_test, Y_pred, average='weighted',zero_division=0)*100

      Results.append([model_name, accuracy,precision,recall,f1])

In [92]:
# Create a DataFrame to store results
Results_df = pd.DataFrame(Results, columns=['Model', 'Accuracy', 'Precision', 'Recall', 'F1-Score'])
Results_df

                 Model   Accuracy  Precision     Recall   F1-Score
0  Logistic Regression  42.369369  42.243826  42.369369  41.232108
1        Decision Tree  32.765766  33.064218  32.765766  32.905917
2        Random Forest  41.576577  37.037710  41.576577  37.630123

In [93]:
#Classification Report and Confusion Matrix for Each Model
for model_name, model in Models.items():
  model.fit(X_train, Y_train)
  Y_pred = model.predict(X_test)
  print(f"Classification Report for {model_name}:")
  print(classification_report(Y_test, Y_pred))
  print(f"Confusion Matrix for {model_name}:")
  print(confusion_matrix(Y_test, Y_pred))
  print("-"*50)

Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.55      0.45      0.49      4021
           1       0.44      0.69      0.54      2656
           2       0.29      0.28      0.28      2363
           3       0.30      0.20      0.24      2060

    accuracy                           0.42     11100
   macro avg       0.39      0.40      0.39     11100
weighted avg       0.42      0.42      0.41     11100

Confusion Matrix for Logistic Regression:
[[1795  822  990  414]
 [ 300 1838  248  270]
 [ 722  706  653  282]
 [ 422  828  393  417]]
--------------------------------------------------
Classification Report for Decision Tree:
              precision    recall  f1-score   support

           0       0.44      0.42      0.43      4021
           1       0.37      0.37      0.37      2656
           2       0.22      0.22      0.22      2363
           3       0.20      0.21      0.21      2060

    accuracy                           0.33     11100
   macro avg       0.31      0.31      0.31     11100
weighted avg       0.33      0.33      0.33     11100

Confusion Matrix for Decision Tree:
[[1681  662  950  728]
 [ 659  991  498  508]
 [ 885  499  526  453]
 [ 629  547  455  429]]
--------------------------------------------------
Classification Report for Random Forest:
              precision    recall  f1-score   support

           0       0.46      0.67      0.55      4021
           1       0.45      0.53      0.49      2656
           2       0.22      0.11      0.15      2363
           3       0.26      0.12      0.17      2060

    accuracy                           0.42     11100
   macro avg       0.35      0.36      0.34     11100
weighted avg       0.37      0.42      0.38     11100

Confusion Matrix for Random Forest:
[[2701  571  455  294]
 [ 799 1407  214  236]
 [1417  499  256  191]
 [ 951  643  215  251]]
--------------------------------------------------

In [94]:
#Evaluating the Importance of Features by using the Random Forest Model
Random_Forest_model = Models['Random Forest']
importances = (Random_Forest_model.feature_importances_)*100
feature_importances = pd.DataFrame({'Feature': x.columns, 'Importance': importances}).sort_values(by='Importance', ascending=False)
print(feature_importances)

                                              Feature  Importance
0                                                 Age   18.777231
1                                         Gender_Male    4.054173
7                                       Blood Type_O+    3.219315
15                          Medical Condition_Obesity    2.882275
16            Hospital_Northwestern Memorial Hospital    2.795379
17                         Hospital_UChicago Medicine    2.742234
18  Hospital_UI Health (University of Illinois Hos...    2.531832
19                      Insurance Provider_Blue Cross    2.510925
40                                Admission Year_2020    2.452131
22                Insurance Provider_UnitedHealthcare    2.429530
21                        Insurance Provider_Medicare    2.403406
20                           Insurance Provider_Cigna    2.375986
42                                Admission Year_2022    2.322930
41                                Admission Year_2021    2.288305
43                                Admission Year_2023    2.211799
28                            Admission Day_Wednesday    2.159577
27                              Admission Day_Tuesday    2.152474
26                             Admission Day_Thursday    2.131344
25                               Admission Day_Sunday    2.126557
24                             Admission Day_Saturday    2.125172
23                               Admission Day_Monday    1.960634
5                                       Blood Type_B+    1.790161
6                                       Blood Type_B-    1.624697
37                                 Admission Month_10    1.578538
38                                 Admission Month_11    1.549162
31                                  Admission Month_4    1.518209
33                                  Admission Month_6    1.510121
30                                  Admission Month_3    1.501361
4                                      Blood Type_AB-    1.488358
32                                  Admission Month_5    1.488011
29                                  Admission Month_2    1.455854
36                                  Admission Month_9    1.454351
35                                  Admission Month_8    1.453867
34                                  Admission Month_7    1.449348
39                                 Admission Month_12    1.439701
13                    Medical Condition_Heart Disease    1.316749
3                                      Blood Type_AB+    1.300318
8                                       Blood Type_O-    1.270244
2                                       Blood Type_A-    1.269862
44                                Admission Year_2024    1.059690
10                           Medical Condition_Cancer    0.992169
9                            Medical Condition_Asthma    0.945212
12                              Medical Condition_Flu    0.680343
14                       Medical Condition_Infections    0.641567
11                         Medical Condition_Diabetes    0.568900